name: Automation

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:        # Allows manual triggering of the workflow

jobs:
  modify-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Check if README contains temporary text
      id: check_text
      run: |
        if grep -q "This is temporary text." README.md; then
          echo "contains_text=true" >> $GITHUB_ENV
        else
          echo "contains_text=false" >> $GITHUB_ENV
        fi

    - name: Add or Remove Text from README
      run: |
        if [ "${{ env.contains_text }}" = "true" ]; then
          # Remove the text if it exists
          sed -i '/This is temporary text./d' README.md
          echo "commit_message=Removed temporary text" >> $GITHUB_ENV
        else
          # Add the text if it doesn't exist
          echo "This is temporary text." >> README.md
          echo "commit_message=Added temporary text" >> $GITHUB_ENV
        fi

    - name: Commit and Push changes
      run: |
        git add README.md
        git commit -m "${{ env.commit_message }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
